const path = require("path");
const S = path.join(__dirname, "..");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require("playwright");
const { execSync } = require("child_process");
const fs = require("fs");
const ARGS = [`--proxy-server=${process.env.HTTPS_PROXY}`, "--proxy-bypass-list=localhost;127.0.0.1", "--enable-unsafe-swiftshader", "--use-angle=swiftshader", "--ignore-gpu-blocklist"];
const check = (label, ok, extra = "") => console.log(`${ok ? "PASS" : "FAIL"} ${label}${extra ? ` (${extra})` : ""}`);
const db = (q) => execSync(`su postgres -c "/usr/lib/postgresql/16/bin/psql -h /var/lib/postgresql/backroute-test -p 55432 -U postgres -d rest -tA -c \\"${q.replace(/"/g, '\\\\\\"')}\\""`).toString().trim();
const pm = () => fs.readFileSync(S + "/fakes/postmark.jsonl", "utf8").trim().split("\n").filter(Boolean).map((l) => JSON.parse(l));
const cid = fs.readFileSync(`${S}/fakes/carrier.txt`, "utf8").trim();
const sub = "aaaaaaaa-0000-0000-0000-000000000001", phone = "12145550100";
(async () => {
  const tok = execSync(`node ${S}/pgrst/jwt.cjs ${sub} ${phone}`).toString();
  const session = JSON.stringify({ access_token: tok, refresh_token: "x", token_type: "bearer", expires_in: 3600, expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: sub, phone, aud: "authenticated", role: "authenticated", app_metadata: {}, user_metadata: {} } });
  const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ARGS });
  const p = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = [];
  p.on("pageerror", (e) => errors.push(e.message));
  p.on("console", (m) => { if (m.type() === "error" && !/osrm|ERR_FAILED|tile|realtime|WebSocket/i.test(m.text())) errors.push(m.text()); });
  await p.goto("http://localhost:3210/login", { waitUntil: "domcontentloaded" });
  await p.evaluate((s) => localStorage.setItem("sb-localhost-auth-token", s), session);
  await p.goto("http://localhost:3210/carrier", { waitUntil: "domcontentloaded" });
  // Two drafts wait: the AI's reply to Dana, and the delay notice about the breakdown. This test answers the reply.
  await p.getByLabel("Reply", { exact: true }).first().waitFor({ timeout: 90000 });
  await p.waitForTimeout(1500);
  const drafts = p.locator('textarea[id^="draft-"]');
  const before = await drafts.count();
  const idx = await drafts.evaluateAll((els) => els.findIndex((e) => e.value.includes("thanks for the rate con")));
  const box = drafts.nth(idx);
  const home = await p.locator("main").innerText();
  check("draft shows in Needs you, marked as email", home.includes("The AI wrote a reply for you to check") && /By email/i.test(home));
  check("breakdown from the call shows, marked as a call", /On a call/i.test(home) && home.includes("Marcus Bell (breakdown)"));
  await p.screenshot({ path: `${S}/.out/approve-before.png` });
  await box.fill("Hi Dana, got the rate con for CFP-88213. Truck 101 will be there Tuesday at 8. Thanks, Titan Freight");
  await box.locator("xpath=..").getByRole("button", { name: "Send", exact: true }).click();
  await p.waitForTimeout(3000);
  const sent = pm().at(-1)?.body;
  check("approved reply emailed to the broker, as edited", sent?.To === "loads@coastalfreight.test" && sent.TextBody.startsWith("Hi Dana") && sent.Subject === "Re: Rate con CFP-88213", sent?.Subject);
  check("sent from the carrier's name, threaded", sent?.From === "Titan Freight LLC <dispatch@backroute.test>" && sent.Headers?.[0]?.Value === "<dana-123@coastal.test>");
  check("draft closed in the database", db(`select status from escalations where carrier_id = '${cid}' and data->'draft' is not null and data->'draft'->>'purpose' = 'reply'`) === "resolved");
  check("draft card gone from Needs you", (await p.getByLabel("Reply", { exact: true }).count()) === before - 1);

  await p.evaluate(() => window.next.router.push("/carrier/settings?tab=general"));
  await p.getByText("Phone, text and email").waitFor({ timeout: 30000 });
  await p.waitForTimeout(2500);
  const settings = await p.locator("main").innerText();
  check("channels card: all on, dispatch number shown", (settings.match(/\bOn\b/g) ?? []).length >= 5 && settings.includes("(469) 555-0199"));
  check("channels card: broker email address with the carrier's key", /abc123\+[a-f0-9]{12}@inbound\.postmarkapp\.com/.test(settings));
  check("channels card: latest texts, calls and emails listed", settings.includes("I'm loaded and rolling") && settings.includes("Hi Dana"));
  await p.getByText("Phone, text and email").scrollIntoViewIfNeeded();
  await p.screenshot({ path: `${S}/.out/channels-card.png` });
  console.log("errors:", errors);
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
