const path = require("path");
const S = path.join(__dirname, "..");
const ROOT = path.join(__dirname, "../..");
const { chromium } = require("playwright");
const { execSync } = require("child_process");
const fs = require("fs");
const ARGS = [`--proxy-server=${process.env.HTTPS_PROXY}`, "--proxy-bypass-list=localhost;127.0.0.1", "--enable-unsafe-swiftshader", "--use-angle=swiftshader", "--ignore-gpu-blocklist"];
const check = (label, ok, extra = "") => console.log(`${ok ? "PASS" : "FAIL"} ${label}${extra ? ` (${extra})` : ""}`);
const db = (q) => execSync(`su postgres -c "/usr/lib/postgresql/16/bin/psql -h /var/lib/postgresql/backroute-test -p 55432 -U postgres -d rest -tA -c \\"${q.replace(/"/g, '\\\\\\"')}\\""`).toString().trim();
const tw = () => fs.readFileSync(S + "/fakes/twilio.jsonl", "utf8").trim().split("\n").filter(Boolean).map((l) => JSON.parse(l));
const sub = "aaaaaaaa-0000-0000-0000-000000000001", phone = "12145550100";
(async () => {
  const tok = execSync(`node ${S}/pgrst/jwt.cjs ${sub} ${phone}`).toString();
  const session = JSON.stringify({ access_token: tok, refresh_token: "x", token_type: "bearer", expires_in: 3600, expires_at: Math.floor(Date.now() / 1000) + 3600, user: { id: sub, phone, aud: "authenticated", role: "authenticated", app_metadata: {}, user_metadata: {} } });
  const browser = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium", args: ARGS });
  const p = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors = [];
  p.on("pageerror", (e) => errors.push(e.message));
  p.on("console", (m) => { if (m.type() === "error" && !/osrm|ERR_FAILED|tile|realtime|WebSocket/i.test(m.text())) errors.push(m.text()); });
  await p.goto("http://localhost:3210/login", { waitUntil: "domcontentloaded" });
  await p.evaluate((s) => localStorage.setItem("sb-localhost-auth-token", s), session);

  // Sign up with a real fleet typed in
  await p.goto("http://localhost:3210/signup", { waitUntil: "domcontentloaded" });
  await p.getByLabel("MC number").waitFor({ timeout: 90000 });
  await p.getByLabel("MC number").fill("548213");
  await p.getByRole("button", { name: "Look up" }).click();
  await p.getByRole("radio", { name: /I have drivers/ }).click();
  await p.getByRole("button", { name: /That's us/ }).click();
  await p.getByRole("heading", { name: "Your trucks and drivers" }).waitFor();
  check("real sign-up asks for the fleet, not a sample ELD import", (await p.getByRole("button", { name: "Samsara" }).count()) === 0);
  await p.getByRole("button", { name: "Next", exact: true }).click();
  check("form refuses empty rows", (await p.getByText("Add the driver's name.").count()) === 1);
  const fill = async (n, v) => { const f = p.getByRole("group").nth(n); for (const [label, value] of Object.entries(v)) { const el = f.getByLabel(label, { exact: true }); if ((await el.evaluate((e) => e.tagName)) === "SELECT") await el.selectOption(value); else await el.fill(value); } };
  await fill(0, { "Driver's name": "Marcus Bell", "Driver's cell number": "(214) 555-0148", "Truck unit number": "101", "Home base city": "Dallas", "Home base state": "TX", "How they run": "otr" });
  await p.getByRole("button", { name: "Another truck" }).click();
  await fill(1, { "Driver's name": "Ana Lopez", "Driver's cell number": "972-555-0163", "Truck unit number": "102", Equipment: "Reefer", "Home base city": "Fort Worth", "Home base state": "TX", "How they run": "regional" });
  await p.getByRole("button", { name: "Next", exact: true }).click();
  await p.getByRole("button", { name: /^Next/ }).click();
  await p.getByRole("button", { name: /Finish/ }).click();
  await p.getByText("You're set up").waitFor({ timeout: 30000 });
  check("done screen doesn't claim sample load-finding", (await p.getByText(/Loads page/).count()) === 1);
  await p.waitForTimeout(4000);
  const cid = db(`select carrier_id from members where user_id = '${sub}'`);
  fs.writeFileSync(S + "/fakes/carrier.txt", cid);
  check("owner phone saved on the carrier", db(`select owner_phone from carriers where id = '${cid}'`) === "12145550100");
  check("exactly the typed trucks saved", db(`select string_agg(unit_number, ',' order by unit_number) from trucks where carrier_id = '${cid}'`) === "101,102");
  check("drivers saved with phones", db(`select string_agg(phone_last10, ',' order by phone_last10) from drivers where carrier_id = '${cid}'`) === "2145550148,9725550163");
  check("no sample loads, calls or messages", db(`select (select count(*) from loads where carrier_id='${cid}') + (select count(*) from dispatch_calls where carrier_id='${cid}') + (select count(*) from driver_messages where carrier_id='${cid}')`) === "0");

  // Add a load from its rate con
  await p.getByRole("link", { name: /Go to your dashboard/ }).click();
  await p.waitForURL(/\/carrier$/);
  await p.waitForTimeout(3000);
  // The page's words, less the fleet map (its truck labels and map credits draw in once the tiles arrive).
  const words = () => p.evaluate(() => { const m = document.querySelector("main").cloneNode(true); m.querySelector('section[aria-labelledby="fleet-map-title"]')?.remove(); return m.innerText; });
  const t1 = await words();
  await p.waitForTimeout(9000);
  const t2 = await words();
  check("no simulation running in a real account", t1 === t2, JSON.stringify({ before: t1.split("\n").filter((x) => !t2.includes(x)), after: t2.split("\n").filter((x) => !t1.includes(x)) }));
  await p.evaluate(() => window.next.router.push("/carrier/loads"));
  await p.getByRole("button", { name: "Add a load" }).click();
  const dialog = p.getByRole("dialog", { name: "Add a load" });
  await dialog.getByLabel("Rate con PDF for the new load").setInputFiles(S + "/fakes/data/ratecon.pdf");
  await dialog.getByText(/Filled in from ratecon.pdf/).waitFor({ timeout: 30000 });
  check("rate con filled the form", (await dialog.getByLabel("Broker", { exact: true }).inputValue()) === "Coastal Freight Partners" && (await dialog.getByLabel("Rate", { exact: true }).inputValue()) === "1850" && (await dialog.getByLabel("Pickup city").inputValue()) === "Dallas");
  const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
  check("appointment times filled from the rate con", (await dialog.getByLabel("Pickup date and time").inputValue()) === `${tomorrow}T08:00` && !!(await dialog.getByLabel("Delivery date and time").inputValue()));
  check("time zone named from the stop's state", (await dialog.getByText("Pickup appointment (Chicago time)").count()) === 1);
  await dialog.getByRole("button", { name: "Add the load" }).click();
  await p.waitForURL(/\/carrier\/loads\/load-/, { timeout: 30000 });
  await p.getByText("Dallas, TX").first().waitFor({ timeout: 30000 });
  await p.waitForTimeout(8000);
  check("load saved, dispatched on truck 101", db(`select stage || '|' || (data->>'referenceNumber') from loads where carrier_id = '${cid}'`) === "dispatched|CFP-88213");
  const ptime = db(`select data->>'pickupAt' from loads where carrier_id = '${cid}'`);
  check("pickup saved as an instant at the stop (8 AM Central = 13:00 UTC)", ptime === `${tomorrow}T13:00:00.000Z`, ptime);
  check("broker contact saved on the load for invoices", db(`select data->>'brokerContactEmail' from loads where carrier_id = '${cid}'`) === "loads@coastalfreight.test");
  check("broker saved for the carrier", db(`select data->>'company' from records where carrier_id = '${cid}' and kind = 'broker'`) === "Coastal Freight Partners");
  const texted = tw().find((x) => x.params.To === "+12145550148" && /New load CFP-88213/.test(x.params.Body));
  check("driver texted about the new load", !!texted, texted?.params.Body);
  await p.screenshot({ path: `${S}/.out/real-load.png` });
  console.log("errors:", errors);
  await browser.close();
})().catch((e) => { console.error(e); process.exit(1); });
