# Settings for running the app against the stand-ins (tests/fakes) and the local test database. Every value is a
# test value pointing at localhost; nothing here reaches a real service. Keys are made per machine by tests/setup.sh.
T="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
export NO_PROXY=localhost,127.0.0.1
export NEXT_PUBLIC_SUPABASE_URL=http://localhost:3002
export NEXT_PUBLIC_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImV4cCI6MTgyMTk4Nzk2N30.9Jxna8DpRpomKTkzvXhtAP304R7f6A-Pxza7_qpdnes
export SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiZXhwIjoxODIxOTg3OTY3fQ.MjZ3X01YU9uTQeGnA6EOOvyedKjPz6fOR3zpMPYE5kE
export ANTHROPIC_API_KEY=test-key
export ANTHROPIC_BASE_URL=http://localhost:3005
export TWILIO_ACCOUNT_SID=ACtest
export TWILIO_AUTH_TOKEN=twilio-secret
export TWILIO_FROM_NUMBER=+14695550199
export TWILIO_API_BASE=http://localhost:3006/2010-04-01
export POSTMARK_SERVER_TOKEN=pm-token
export POSTMARK_API_BASE=http://localhost:3007
export EMAIL_FROM=dispatch@backroute.test
export EMAIL_INBOUND_ADDRESS=abc123@inbound.postmarkapp.com
export EMAIL_WEBHOOK_TOKEN=email-hook-secret
export CRON_SECRET=cron-secret
export PUBLIC_BASE_URL=http://localhost:3210
export FMCSA_WEB_KEY=fmcsa-test-key
export FMCSA_API_BASE=http://localhost:3008/qc/services
export SAMSARA_API_BASE=http://localhost:3009/samsara
export MOTIVE_API_BASE=http://localhost:3009/motive
export SUPPORT_PHONES=+13125550100
export GOOGLE_PLACES_API_KEY=places-key
export PLACES_API_BASE=http://localhost:3009/places
export CARE_HOURS=0-24
export RATES_API_URL='http://localhost:3009/rates?o={{originCity}},{{originState}}&d={{destinationCity}},{{destinationState}}&e={{equipment}}'
export RATES_API_HEADER='x-rates-key: rates-key'
export RATES_RPM_PATH=lane.rpm
export RATES_HIGH_PATH=lane.high
export RATES_API_NAME='Test rates'
export HERE_API_KEY=here-key
export HERE_GEOCODE_BASE=http://localhost:3009/here-geocode
export HERE_ROUTER_BASE=http://localhost:3009/here-router
export EVAL_SECRET=eval-secret
export CREDIT_API_URL='http://localhost:3009/credit?mc={{mc}}'
export CREDIT_API_HEADER='x-credit-key: credit-key'
export CREDIT_SCORE_PATH=data.score
export CREDIT_DAYS_PATH=data.dtp
export CREDIT_API_NAME=TestCredit
export PORTAL_WORKER_SECRET=portal-secret
export PORTAL_ALLOW_HTTP=1
export VAPID_SUBJECT=mailto:ops@backroute.test
export STRIPE_SECRET_KEY=sk_test_backroute
export STRIPE_WEBHOOK_SECRET=whsec_backroute_test
export STRIPE_PRICE_PER_TRUCK=price_truck
export STRIPE_API_BASE=http://localhost:3009/stripe
export BILLING_REQUIRED=1
export BILLING_TRIAL_DAYS=14
export SUPPORT_EMAIL=alerts@backroute.test
export NODE_EXTRA_CA_CERTS="$T/.out/push-cert.pem"
export ALERT_PHONES=+13125550199
export TWILIO_WHATSAPP_FROM=+14695550177
export TWILIO_WHATSAPP_TEMPLATE_SID=HXtemplate123
export NEXT_PUBLIC_WHATSAPP_NUMBER=+14695550177
export DEEPGRAM_API_KEY=dg-key
export DEEPGRAM_API_BASE=http://localhost:3009/deepgram
export ELEVENLABS_API_KEY=el-key
export ELEVENLABS_VOICE_ID=voice-1
export ELEVENLABS_BASE=http://localhost:3009/elevenlabs
export WEATHER_API_BASE=http://localhost:3009/weather
export BRIEF_HOURS=0-24
export APP_LINK_HOURS=0-24
export REVIEW_DAY=any
export REVIEW_HOURS=0-24
export QUIET_HOURS=0-0
export UNDO_SECONDS=0
export WEATHER_CA_API_BASE=http://localhost:3009/weather-ca
export PARKING_API_BASE=http://localhost:3009/parking
export PARKING_API_KEY=parking-key
export QBO_CLIENT_ID=qbo-id
export QBO_CLIENT_SECRET=qbo-secret
export QBO_AUTH_URL=http://localhost:3009/qbo/authorize
export QBO_TOKEN_URL=http://localhost:3009/qbo/token
export QBO_REVOKE_URL=http://localhost:3009/qbo/revoke
export QBO_API_BASE=http://localhost:3009/qbo
# Made by tests/setup.sh: the push certificate, the website-password vault key and the push (VAPID) keys.
[ -f "$T/.out/keys.sh" ] && source "$T/.out/keys.sh"
