process.env.PORTAL_VAULT_KEY = Buffer.alloc(32, 7).toString("base64");
const v = await import("../../src/lib/portal/vault.ts");
let pass = 0, fail = 0;
const ok = (l: string, c: boolean) => { if (c) pass++; else fail++; console.log(`${c ? "PASS" : "FAIL"} ${l}`); };
ok("RFC 6238 vector at t=59s", v.totpCode("GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ", 59_000) === "287082");
ok("RFC 6238 vector at t=1111111109s", v.totpCode("GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ", 1111111109_000) === "081804");
ok("a bad key gives no code", v.totpCode("not base32!") === null);
const sealed = v.seal("hunter2", "c1|login|a.com|secret");
ok("sealed text doesn't contain the secret", !sealed.includes("hunter2") && sealed.startsWith("v1."));
ok("opens for its own row", v.open(sealed, "c1|login|a.com|secret")?.value === "hunter2");
ok("won't open for another row", v.open(sealed, "c2|login|a.com|secret") === null);
const parts = sealed.split(".");
parts[3] = parts[3].slice(0, -2) + (parts[3].endsWith("A") ? "BB" : "AA");
ok("tampered text won't open", v.open(parts.join("."), "c1|login|a.com|secret") === null);
process.env.PORTAL_VAULT_KEY_OLD = process.env.PORTAL_VAULT_KEY;
process.env.PORTAL_VAULT_KEY = Buffer.alloc(32, 9).toString("base64");
const o = v.open(sealed, "c1|login|a.com|secret");
ok("after a key change, the old key still opens it (marked for re-sealing)", o?.value === "hunter2" && o?.stale === true);
ok("site names", v.siteOf("https://WWW.MyCarrierPackets.com/x?y") === "mycarrierpackets.com" && v.onSite("login.rmis.com", "rmis.com") && !v.onSite("evilrmis.com", "rmis.com"));
const pw = v.newPassword();
ok("new passwords are strong and differ", pw.length >= 18 && /[A-Z]/.test(pw) && /\d/.test(pw) && /[^\w]/.test(pw) && pw !== v.newPassword());
console.log(`${pass} passed, ${fail} failed`);
process.exit(fail ? 1 : 0);
